project:
  type: website
  output-dir: docs

website:
  title: "Sérgio Bacelar"
  favicon: images/favicon.png
  navbar:
    background: light
    search: true
    left:
      - href: index.qmd
        text: Home
      - about.qmd
      - experience.qmd
      - publications.qmd
      - talks.qmd
      - teaching.qmd
      - contact.qmd
    tools:
      - icon: github
        href: https://github.com/yourusername
  page-footer: 
    left: "© 2024 Sérgio Bacelar"
    right: 
      - icon: github
        href: https://github.com/yourusername

format:
  html:
    theme:
      light: [cosmo, custom.scss]
    css: styles.css
    toc: true
    code-copy: true
    code-overflow: wrap
    mainfont: "Open Sans"