name: Publish Website

on:
  push:
    branches: [main]
  workflow_dispatch:

jobs:
  publish:
    runs-on: ubuntu-latest
    permissions:
      contents: write  # Ensures the action has permission to push
      pages: write     # Needed for GitHub Pages deployment
      id-token: write  # Required for authentication

    steps:
      - name: Check out repository
        uses: actions/checkout@v4  # Updated to the latest version

      - name: Set up Quarto
        uses: quarto-dev/quarto-actions/setup@v2
        with:
          version: pre-release

      - name: Install R
        uses: r-lib/actions/setup-r@v2
        with:
          r-version: '4.4.2'

      - name: Render Site
        run: |
          quarto render  # This generates the site files

      - name: Upload artifact for GitHub Pages
        uses: actions/upload-pages-artifact@v2  # Updated version
        with:
          path: docs  # Ensure this matches your Quarto output directory

  deploy:
    needs: publish
    runs-on: ubuntu-latest
    permissions:
      pages: write
      id-token: write

    steps:
      - name: Deploy to GitHub Pages
        uses: actions/deploy-pages@v4  # Updated to the latest version

