name: Publish Website

on:
  push:
    branches: [main]
  workflow_dispatch:

jobs:
  publish:
    runs-on: ubuntu-latest
    permissions:
      contents: write  # Ensures the action has permission to push
      pages: write     # Required for GitHub Pages deployment
      id-token: write  # Needed for authentication

    steps:
      - name: Check out repository
        uses: actions/checkout@v4  # Updated to latest version

      - name: Set up Quarto
        uses: quarto-dev/quarto-actions/setup@v2
        with:
          version: pre-release

      - name: Install R
        uses: r-lib/actions/setup-r@v2
        with:
          r-version: '4.4.2'

      - name: Render Site
        run: |
          quarto render  # Ensures the website is built properly

      - name: Upload artifact (Quarto site)
        uses: actions/upload-artifact@v4  # Latest artifact action
        with:
          name: website-build
          path: docs  # Ensure this matches your Quarto output directory

  deploy:
    needs: publish
    runs-on: ubuntu-latest
    permissions:
      pages: write
      id-token: write

    steps:
      - name: Download the artifact
        uses: actions/download-artifact@v4
        with:
          name: website-build
          path: docs

      - name: Deploy to GitHub Pages
        uses: actions/deploy-pages@v4  # Latest GitHub Pages deploy action



